### ISSUE TITLE
README.md 내용 추가 요청

### ISSUE THREAD

**Issue by bluebright** [opdev1004/mdblogger#7]
안녕하세요. 요청사항이 있어 이슈 남겨요.

README 내용에 광고 제거 프로그램의 필터링 기능을 OFF 해야 된다는 내용 추가를 요청합니다.

저는 "Adguard" 프로그램 사용 중인데, (필터링 기능이) 활성화되는 동안, 확장프로그램이 작동하지 않는 증상을 확인했습니다.
(#4 이슈("새로고침")와는 별개로 버튼 레이아웃이 깨지는 증상이 있었습니다.)

"Adguard" 프로그램의 "필터 편집기"에 blogger 사이트를 "필터링 예외"에 추가하면 해결되는 것을 확인했습니다.
다만, 모든 광고 제거 프로그램에서도 같은 현상이 나타나는지는 확인해보지 못했습니다.

**Comment by opdev1004** [comment]
이슈 감사합니다. 광고 차단 확장 프로그램들이 요소 삽입이나 확장 프로그램을 막는 걸 고려하지 못했네요.
이야기 하신 대로, 광고 차단 확장 프로그램들 필터링 예외를 요청하는 게 나을 것 같습니다.
무적의 창과 방패의 싸움을 하고 싶지는 않네요. 😄
Readme.md는 수정하겠습니다.

**Comment by opdev1004** [comment]
Resolved in v0.0.5
