### ISSUE TITLE
포스트 수정모드 진입시 기존 하이퍼링크가 "#"으로 교체됩니다.

### ISSUE THREAD

**Issue by bluebright** [opdev1004/mdblogger#8]
이미 작성된 포스트의 수정하기 위해 edit 모드에 진입을 하면,  소괄호 안에 있는 URL이 모두 "#"으로 교체되는 증상이 있습니다.
로그인 정보를 삭제한 후 (쿠키 삭제) 재시도 해봐도 증상은 동일합니다.

```
Markdown URL
[주소 설명 텍스트](URL) → [주소 설명 텍스트](#)
```

**Comment by opdev1004** [comment]
이게 저도 알고 있고 고치고 싶은 버그인데,
마크다운 에디터에서 제공하는 url의 양식과 구글에서 제공하는 에디터의 url 양식이 달라서 그렇습니다.
변환하기 전에 양식을 조정하던지 방법을 생각해보겠습니다.

**Comment by opdev1004** [comment]
Resolved in v0.0.5

**Comment by opdev1004** [comment]
Resolved in v0.0.5
