### ISSUE TITLE
I found a way that juice write pure Markdown text in blogger HTML mode

### ISSUE THREAD

**Issue by crazypeace** [opdev1004/mdblogger#9]
I found a way that just write pure Markdown text in blogger HTML mode  
https://www.youtube.com/watch?v=UjhAkpdcQ4o

Demo page  
https://use-markdown-in.blogspot.com/2024/10/markdown-demo.html

**Comment by opdev1004** [comment]
That seems okay. Good work around.

But it may not work when the script hosting is disabled. Which is rare, but still can happen for github when there are many request. Another problem is, it does not provide markdown preview and does not provide wysiwyg editor.

**Comment by crazypeace** [comment]
Yes, your point is correct.  

But about the script hosting, I consider these,
1. Github is a big company and has M$ behind, so I think Github's server is strong.
2. Another way is to use Cloudflare's Pages or Worker. Also strong sever.
3. Everyone can host the script file by themselves.
